- README.md
update readme.md package description
change the packages name from `react` to `vue`
---
> chore: fix README package name

- package.json
- playground/package.json
- playground/ssr-vue/dep-import-type/package.json
- playground/ssr-vue/example-external-component/package.json
- playground/ssr-vue/package.json
- playground/ssr-vue/src/components/ImportType.vue
- playground/ssr-vue/src/pages/External.vue
- playground/ssr-vue/vite.config.js
- playground/ssr-vue/vite.config.noexternal.js
- playground/vue-jsx/package.json
- playground/vue-legacy/package.json
- playground/vue-lib/package.json
- playground/vue-server-origin/package.json
- playground/vue-sourcemap/package.json
- playground/vue/package.json
- pnpm-lock.yaml
Same with https://github.com/vitejs/vite/pull/11172
---
> chore: rename test packages

- package.json
- pnpm-lock.yaml
https://github.com/evanw/esbuild/releases/tag/v0.16.3
---
> chore(deps): esbuild 0.16.3

- package.json
- pnpm-lock.yaml
Simply removed not used deps.
---
> chore: remove not used deps

- playground/vue/__tests__/vue.spec.ts
Fixing little bug in test case described in #86
---
> test: "absolute import" test case bug (fix #86)

- packages/plugin-vue/src/main.ts
> fix(vue): retrieve rewritten code

- .npmrc
Removed unneeded hoist patterns.
refs https://github.com/vitejs/vite/pull/13069 https://github.com/vitejs/vite-plugin-react/pull/157
---
> chore: cleanup hoist patterns

- playground/vue-sourcemap/__tests__/__snapshots__/vue-sourcemap.spec.ts.snap
- playground/vue-sourcemap/__tests__/vue-sourcemap.spec.ts
This PR reverts #119 and updates snapshots.
---
> chore: restore sourcemap tests

- packages/plugin-vue-jsx/src/index.ts
> refactor(plugin-vue-jsx): improve the readability

- .eslintrc.cjs
- .github/workflows/ci.yml
- package.json
- packages/plugin-vue-jsx/package.json
- packages/plugin-vue/package.json
- vitest.config.e2e.ts
- vitest.config.ts
> refactor!: drop node 14&16

- packages/plugin-vue/src/script.ts
There are simplified functions available for resolving the `clientCache` or `ssrCache`, but the code in `resolveScript` still directly utilizes the cache. This pull request aims to replace the old code with `getResolvedScript` and `setResolvedScript`.
---
> refactor(plugin-vue): simplify logic of resolving script

- README.md
> docs: fix broken node.js release link

- packages/plugin-vue/src/utils/descriptorCache.ts
Use vite's normalizePath for path consistency.
---
> refactor(plugin-vue): use normalizePath from vite

- packages/plugin-vue/src/index.ts
- packages/plugin-vue/src/script.ts
Add a `features` option to configure compile-time flags and future SFC compiler features.
---
> feat(plugin-vue): add `features` option

- packages/plugin-vue-jsx/src/index.ts
- packages/plugin-vue-jsx/src/types.ts
support tsPluginOptions
https://babel.nodejs.cn/docs/babel-plugin-transform-typescript/
https://github.com/babel/babel/issues/16373
---
> feat: support tsPluginOptions

- packages/plugin-vue-jsx/package.json
- packages/plugin-vue/package.json
- playground/vue-legacy/package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
update Vite peer dep to `^5.0.0 || ^6.0.0` from `^5.0.0`.
---
> chore: add vite 6 peer dep

- playground/tailwind/tailwind.config.js
Same with https://github.com/vitejs/vite/pull/18969
---
> test: use ESM syntax in tailwind config

- packages/plugin-vue/src/index.ts
> fix(plugin-vue): suppress warnings for non-recognized pseudo selectors form lightningcss

- packages/plugin-vue/src/main.ts
> fix(plugin-vue): support vapor template-only component

- packages/plugin-vue/src/utils/descriptorCache.ts
Reverts vitejs/vite-plugin-vue#538
> Revert "fix: generate unique component id"

- .github/renovate.json5
Same with https://github.com/vitejs/vite/pull/19654.
---
> ci: pin commit for actions

- packages/plugin-vue/src/style.ts
To fix this type error
https://github.com/vitejs/vite-ecosystem-ci/actions/runs/14164421251/job/39675092493#step:8:806
---
> chore: fix types with Vite 6.3

- packages/plugin-vue/src/main.ts
For detailed information, please refer to vitejs/vite#19689
---
> fix(plugin-vue): when the resource path contains chinese characters, dev/build is inconsistent

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/workflows/issue-labeled.yml
Set issue types `bug` / `feature` by issue template and remove `enhancement: pending` label.
---
> chore: set issue types and remove "enhancement: pending" label

- eslint.config.js
- playground/package.json
- playground/ssr-vue/__tests__/ssr-vue.spec.ts
- playground/tailwind-v3/package.json
- playground/tailwind/package.json
- pnpm-lock.yaml
> chore: remove unused deps

- playground/vue/vite.config.ts
fixes this ecosystem-ci failure: https://github.com/vitejs/vite-ecosystem-ci/actions/runs/15061007152/job/42336016840#step:8:901
---
> chore: remove splitVendorChunkPlugin from tests

- packages/plugin-vue-jsx/package.json
- packages/plugin-vue/package.json
> chore: add `description` and `keywords` field to package.json

- packages/plugin-vue-jsx/src/index.ts
> fix(jsx): vite 5 / 6 compat

- package.json
Added the needed `onlyBuiltDependencies`.
> chore: update onlyBuiltDependencies
