package.json
pnpm-lock.yaml

There is an issue with pnpm and corepack that is preventing us to properly run vite-ecosystem-ci. Updating to 7.18.1 across all projects will fix this problem.
---

chore: update pnpm to 7.18.1

---

playground/vue-sourcemap/__tests__/vue-sourcemap.spec.ts

Temporal skip of outdated sourcemaps to avoid false negatives on ecosystem-ci after 
- https://github.com/vitejs/vite/pull/12079
Reference run of plugin-vue: https://github.com/vitejs/vite-ecosystem-ci/actions/runs/4300266958/jobs/7496308552
---

chore: skip sourcemap tests after vitejs/vite/pull/12079

---

playground/ssr-vue/__tests__/ssr-vue.spec.ts

This PR fixes https://github.com/vitejs/vite-ecosystem-ci/actions/runs/4401589281/jobs/7707930360#step:8:419
https://github.com/vitejs/vite/pull/12324 removed passing `e.stack` to `server.config.logger.error`. So `THROW_MESSAGE` is no longer output.
---

chore: remove expect error message

---

packages/plugin-vue/src/main.ts

Reuse the AST and MagicString instance from `resolveScript`.
Please don't merge it until the [upstream PR](https://github.com/vuejs/core/pull/7068) got merged and released.
https://github.com/vitejs/vite/pull/10888
https://github.com/vuejs/core/pull/7068#pullrequestreview-1177957635
---

refactor: reuse script ast for rewriting default

---

packages/plugin-vue/src/index.ts

Expose `hoistStatic` option in `script` options.
---

feat(types): expose `hoistStatic` option for script compilation

---

packages/plugin-vue/src/template.ts
playground/vue/Main.vue
playground/vue/PreProcessorsHmr.vue
playground/vue/__tests__/vue.spec.ts

Fixes #28 and #76.
When using pug as a template preprocessor and if you update both script and template at the same time, you will get
```
Property "foo" was accessed during render but is not defined on instance.
```
as a browser console error instead of hmr updating properly.
This is because the template compilation relies on the compiled script being already in cache, which in this case it isn't, because the hmr requests both template and script modules at the same time (see #28 for timing).
This fix makes sure that the script cache is always populated before the template is compiled.
I'm not sure if calling `resolveScript` on every template `compile` is overkill, but `resolveScript` has an early return if there is already cached result. I could not get the relevant context …

fix(plugin-vue): hmr not working when updating script+template at the same time with a template preprocessor

---

packages/plugin-vue/README.md
packages/plugin-vue/src/index.ts

https://github.com/vuejs/core/commit/4e028b966991937c83fb2529973fd3d41080bb61
Added the possibility to define `globalTypeFiles` for the `vue/compiler-sfc`. However, this plugin is still missing the new type.
I am relatively new to the vue ecosystem. So I hope I added it to all the necessary places..
---

fix: missing typescript declaration for globalTypeFiles

---

packages/plugin-vue/src/main.ts
packages/plugin-vue/src/script.ts
packages/plugin-vue/src/template.ts
playground/vue/DefaultLangs.vue
playground/vue/Main.vue
playground/vue/__tests__/vue.spec.ts
playground/vue/tsconfig.json

Resolved merge conflicts for https://github.com/vitejs/vite-plugin-vue/pull/65.
---
```vue
<template lang="html">
<div>foo</div>
</script>
```
and
```
<script setup lang="js">
const foo = 'foo'
</script>
```
didn't work.
This PR fixes these.
requires https://github.com/vuejs/core/issues/7388
fixes https://github.com/vitejs/vite-plugin-vue/issues/17
---

fix: make it work when a default lang was specified

---

playground/tailwind/App.vue
playground/tailwind/PugTemplate.vue
playground/tailwind/__tests__/tailwind.spec.ts
playground/tailwind/index.css
playground/tailwind/index.html
playground/tailwind/package.json
playground/tailwind/postcss.config.ts
playground/tailwind/tailwind.config.js
playground/tailwind/vite.config.ts
pnpm-lock.yaml

Migrated tailwind + pug test (https://github.com/vitejs/vite/pull/6987) from Vite main repo.
I tested that this test fails if this part is removed.
https://github.com/vitejs/vite-plugin-vue/blob/1e8d16ecbdc33c21a038948c2dd9ac7791df1508/packages/plugin-vue/src/handleHotUpdate.ts#L142-L147
refs https://github.com/vitejs/vite/issues/11175
---

test: migrate tailwind + pug test from Vite repo

---

packages/plugin-vue/src/handleHotUpdate.ts
packages/plugin-vue/src/main.ts
packages/plugin-vue/src/utils/descriptorCache.ts

Distinguish HMR and transform descriptor
Transform descriptors are not the same as HMR descriptors. Transform one will be transformed by Vite plugin, but HMR one is read from filesystem directly (without transform)
---

fix(plugin-vue): distinguish HMR and transform descriptor

---

playground/ssr-vue/vite.config.noexternal.js

fix: playground/vue-ssr external config merge

---

packages/plugin-vue/README.md

Add example for [transforming custom blocks](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue#example-for-transforming-custom-blocks)
close #208

docs: add example for transforming custom blocks

---

packages/plugin-vue-jsx/src/index.ts

Since we don't need to get the hash from the source, there is no need to pass it.
---

chore: remove unused function parameter

---

packages/plugin-vue/src/main.ts

Imported the 'fs' module and added a conditional check using `fs.existsSync()` to ensure that the `getDescriptor()` function is only called when the file exists. This prevents errors when the file doesn't exist and improves the overall functionality.
---

fix: conditionally get descriptor on hmr

---

packages/plugin-vue/src/index.ts

To fix https://github.com/vitejs/vite/pull/13944#issuecomment-1648267307
---

chore: add `@ts-ignore` when accessing `legacy?.buildSsrCjsExternalHeuristics`

---

playground/ssr-vue/__tests__/serve.ts
playground/ssr-vue/__tests__/ssr-vue.spec.ts
playground/ssr-vue/package.json
playground/ssr-vue/prerender.js
playground/ssr-vue/server.js

Set SSR manifest path so that the test passes after https://github.com/vitejs/vite/pull/14230 is merged.
---

chore: set ssr manifest path

---

packages/plugin-vue/src/index.ts

fix(plugin-vue): re-create filters after updating options

---

packages/plugin-vue/src/index.ts
playground/ssr-vue/__tests__/ssr-vue.spec.ts
playground/vue-server-origin/__tests__/vue-server-origin.spec.ts
playground/vue/__tests__/vue.spec.ts

Changes to make tests pass after https://github.com/vitejs/vite/pull/14508 is merged.
---

chore: make tests pass with rollup4

---

playground/vue/vite.config.ts

Decrease the `assetsInlineLimit` for now since SVGs in Vite 5 are now inlined which breaks:
https://github.com/vitejs/vite-plugin-vue/blob/298d419bbb2c2402a4b2745343abd09c5f3e5814/playground/vue/__tests__/vue.spec.ts#L162
This fix should work in both Vite 4 and 5.
---

test: update config to support vite 5

---

packages/plugin-vue/package.json

Vite 5 will be released today.
A new major could also be done in case we want to drop Node 16 already, but we can already support Vite 5 with a patch.
---

chore: update peerDependencies to support Vite 5

---

packages/plugin-vue/src/handleHotUpdate.ts
packages/plugin-vue/src/template.ts
playground/vue/__tests__/vue.spec.ts

This PR adds a check for the updated script's AST during HMR so that if the AST contains merely location or comment changes, the script would be excluded from `affectedModules` (thus skipping HMR).
---

feat: skip hmr when script is merely formatted

---

packages/plugin-vue/src/template.ts

In Astro, it has its own image handling that returns image imports as an object, rather than a string. This would break when Vue automatically transform asset reference to imports.
However, when we try to disable with `transformAssetUrls: false`, it didn't work due to the logic flow, and always enabled it anyways. This PR fixes it.
There is a workaround today (https://github.com/withastro/astro/issues/9328#issuecomment-1842752441), but I figured it's better to improve this anyway.
---

fix(plugin-vue): allow disabling transformAssetUrls

---

packages/plugin-vue/src/main.ts
packages/plugin-vue/src/script.ts

Ensure that the `setup` section is available in Vuejs Devtools when building with `__VUE_PROD_DEVTOOLS__: true`.
Original fix. Possible regression since then? https://github.com/vitejs/vite/pull/4984
Another report with example reproduction: https://github.com/vuejs/devtools/issues/1940
Not sure if `defineExpose` is supposed to play a role here.
---

fix(plugin-vue): don't inline template when `__VUE_PROD_DEVTOOLS__`

---

packages/plugin-vue/src/main.ts

fix(plugin-vue): Support decorators in .vue file.
issues: https://github.com/vitejs/vite-plugin-vue/issues/430
More thoughts:
```
      {
        target: 'esnext',
        // #430 Support decorators in .vue file. https://github.com/vitejs/vite-plugin-vue/issues/430
        // target can be overridden by esbuild config target
        ...options.devServer?.config.esbuild,
        loader: 'ts',
        sourcemap: options.sourceMap,
      },
```
in vite-plugin-vue，There is no merge from esbuildTransformOptions, so submit the modification and merge esbuildTransformOptions, that is, options.devServer?.config.esbuild in the development environment
in vite vite:esbuild，Merged from esbuildTransformOptions
Just for fault tolerance and compatibility considerations
vite is the basic component of …

fix(plugin-vue): allow overwrite esbuild config

---

packages/plugin-vue/src/handleHotUpdate.ts

fix https://github.com/vuejs/core/issues/11923
The types imported from third-party libraries can be quite complex, and comparing them for equality is time-consuming.
---

fix: skip checking private properties of typeParameters

---

packages/plugin-vue-jsx/src/index.ts
packages/plugin-vue/src/utils/descriptorCache.ts

Excerpted from https://github.com/vitejs/vite/pull/18317
---

perf: use `hash` to replace `createHash`

---

playground/vue-lib/vite.config.lib.ts

Vite 6 library mode css file name now derives from the `package.json` `"name"` by default instead of always being `style.css`. This PR handles this case to work in both vite 5 and 6 by setting the new `build.lib.cssFileName` property.
---

test: handle vue-lib fixture for vite 6

---

playground/package.json
playground/tailwind/package.json
playground/tailwind/postcss.config.cts
playground/vue-asset-base/package.json
playground/vue-jsx/package.json
playground/vue-jsx/vite.config.js
playground/vue-legacy/package.json
playground/vue-lib/package.json
playground/vue-server-origin/package.json
playground/vue-sourcemap/SassWithImport.vue
playground/vue-sourcemap/__tests__/__snapshots__/vue-sourcemap.spec.ts.snap
playground/vue-sourcemap/package.json
playground/vue-sourcemap/postcss.config.js
playground/vue-sourcemap/src-import/src-import.sass
playground/vue/package.json

- Use `"type": "module"` to remove Vite's CJS deprecation message
- Update `postcss.config.js` to handle ESM/CJS syntax
- Update scss to `@use` instead if `@import` as its deprecated (logs a warning in vite 6)
---

test: remove deprecation warnings

---

packages/plugin-vue/src/index.ts
packages/plugin-vue/src/main.ts
playground/vue/Hmr.vue
playground/vue/__tests__/vue.spec.ts
playground/vue/lib.js

close #7 
close #8 
close #386
see https://github.com/vitejs/vite-plugin-vue/issues/7#issuecomment-2464268934
---

fix(hmr): should reload if relies file changed after re-render

---

playground/vue/__tests__/vue.spec.ts

test: fix flaky should reload test fail

---

packages/plugin-vue/src/index.ts
pnpm-lock.yaml

close #480 
refix #438
According to the docs https://vuejs.org/api/compile-time-flags.html#rollup, their values are strings, and converting `'false'` to a boolean will result in true.
---

fix(plugin-vue): default value for compile time flags

---

packages/plugin-vue/src/index.ts

move if check before ssr constant creation to prevent redundant initialization when entering return block
---

fix(index): move the if check earlier to avoid creating unnecessary ssr when entering return block

---

packages/plugin-vue/src/index.ts
playground/vue-external/src-import/SrcImport.vue
playground/vue-external/src-import/css.module.css
playground/vue-external/src-import/script.ts
playground/vue-external/src-import/srcImportModuleStyle.vue
playground/vue-external/src-import/srcImportModuleStyle2.vue
playground/vue-external/src-import/srcImportStyle.vue
playground/vue-external/src-import/srcImportStyle2.vue
playground/vue-external/src-import/style.css
playground/vue-external/src-import/style2.css
playground/vue-external/src-import/template.html
playground/vue/Main.vue
playground/vue/__tests__/vue.spec.ts
playground/vue/vite.config.ts

Currently vue-plugin ignore watcher and use default vite config for it (root without node_modules), it not worked for monorepo's. And hmr not worked for shared script/style with src like this, but worked for .vue (reason later)
```
// node_modules/shared/index.vue
<template>
<div> foo</div>
</template>
<script src="./index.ts"></script>
// node_modules/shared/index.ts
export default defineComponent({
...
})
```
In contrast of this internal vite-esbuild plugin add imports to watcher (because of it `.vue` hmr worked, because it imports from ts/js)
fix #397 
By default `vite` doesn't support hmr for `node_modules`, we enable it by https://github.com/vitejs/vite/issues/8619#issuecomment-2606507049
---

fix(plugin-vue): support external import URLs for monorepos

---

packages/plugin-vue/src/handleHotUpdate.ts
packages/plugin-vue/src/index.ts
playground/vue/ExportTypeProps1.vue
playground/vue/ExportTypeProps2.vue
playground/vue/Main.vue
playground/vue/__tests__/vue.spec.ts

close https://github.com/vuejs/core/issues/13008
Fix HMR when an SFC exporting a type is treated as a type dependency. Ensure the SFC itself triggers an update instead of relying only on type dependency handling, preventing outdated transforms from applying and causing incorrect updates. 
---

fix(plugin-vue): ensure HMR updates styles when SFC is treated as a type dependency

---

packages/plugin-vue-jsx/src/index.ts
packages/plugin-vue/src/index.ts

Previously, `config.define` values like `"false"` were mistakenly treated as `true` in subsequent evaluations, leading to incorrect behavior
---

fix: properly interpret boolean values in `define`

---

packages/plugin-vue/src/utils/descriptorCache.ts

---
The component id using hash for relative path, it could be conflict at module federation. The pr using the absolute path to avoid it.

fix: generate unique component id

---

packages/plugin-vue/src/index.ts

fix(plugin-vue): resolve sourcemap conflicts in build watch mode with cached modules

---

packages/plugin-vue/src/index.ts
packages/plugin-vue/src/main.ts
packages/plugin-vue/src/style.ts
packages/plugin-vue/src/utils/descriptorCache.ts
playground/ssr-vue/vite.config.js
playground/vue/Main.vue
playground/vue/TreeShakeScopedStyle.vue
playground/vue/__tests__/vue.spec.ts

Since the scoped styles in Vue generates styles scoped to that component, it can be tree shaken if that component is not used. (normal styles cannot be tree shaken as it can be used from other components).
This PR requires https://github.com/vitejs/vite-plugin-vue/pull/526 and it uses a recently introduced feature in Vite (https://github.com/vitejs/vite/pull/19418).
I tested this feature with https://vitepress.new/ and I got 8kB CSS file reduction.
Technically you can have a scoped style like below
```css
:global(.foo) {
color: red;
}
```
and this would be treeshaken where you might not expect to. If we should handle this case, we can add an additional condition of `!code.includes(':global')`.
---

feat(css): tree shake scoped styles

---

playground/ssr-vue/__tests__/ssr-vue.spec.ts

this is deprecated and a warning was output.
https://vitest.dev/guide/migration.html#test-options-as-a-third-argument
---

test: fix deprecated third argument options

---

packages/plugin-vue/src/main.ts
packages/plugin-vue/src/style.ts
packages/plugin-vue/src/template.ts
packages/plugin-vue/src/utils/error.ts
playground/vitestSetup.ts
playground/vue-lib/__tests__/vue-lib.spec.ts

Use rollup types exposed from Vite. This will make ecosystem-ci w/ rolldown-vite run without type errors (one test fail due to lib mode not supported).
The rollup types were exposed since Vite 4.2.0 (https://github.com/vitejs/vite/commit/6e49e5284a5ee5bdae801d2fcbd594a49a7694b4). This is fine because plugin-vue only supports Vite 5+.
---

chore: use rollup types exposed from Vite

---

packages/plugin-vue/src/main.ts
playground/vue-sourcemap/EmptyScript.vue
playground/vue-sourcemap/__tests__/__snapshots__/vue-sourcemap.spec.ts.snap
playground/vue-sourcemap/__tests__/vue-sourcemap.spec.ts

close https://github.com/vuejs/core/issues/13260
- [Before](https://evanw.github.io/source-map-visualization/#MTMzMwBpbXBvcnQgeyBjcmVhdGVIb3RDb250ZXh0IGFzIF9fdml0ZV9fY3JlYXRlSG90Q29udGV4dCB9IGZyb20gIi9Adml0ZS9jbGllbnQiO2ltcG9ydC5tZXRhLmhvdCA9IF9fdml0ZV9fY3JlYXRlSG90Q29udGV4dCgiLi9maXh0dXJlcy9maWZ0aC52dWUiKTtjb25zdCBfc2ZjX21haW4gPSB7ICB9CmltcG9ydCB7IG9wZW5CbG9jayBhcyBfb3BlbkJsb2NrLCBjcmVhdGVFbGVtZW50QmxvY2sgYXMgX2NyZWF0ZUVsZW1lbnRCbG9jaywgY3JlYXRlQ29tbWVudFZOb2RlIGFzIF9jcmVhdGVDb21tZW50Vk5vZGUgfSBmcm9tICIvbm9kZV9tb2R1bGVzLy52aXRlL2RlcHMvdnVlLmpzP3Y9YzNiN2NlOTkiCgpjb25zdCBfaG9pc3RlZF8xID0geyBrZXk6IDAgfQoKZnVuY3Rpb24gX3NmY19yZW5kZXIoX2N0eCwgX2NhY2hlKSB7CiAgcmV0dXJuIChfb3BlbkJsb2NrKCksIF9jcmVhdGVFbGVtZW50QmxvY2soImRpdiIsIG51bGwsIFsKICAgICgxICsgMyA9PT0gMikKICAgICAgPyAoX29wZW5CbG9jaygpLCBfY3JlYX …

fix(plugin-vue): handle sourcemap with empty script code

---

packages/plugin-vue/src/main.ts

When [using `rolldown-vite`](https://vite.dev/guide/rolldown#transformwithesbuild-requires-esbuild-to-be-installed-separately), one needs to install esbuild at the moment as `transformWithEsbuild` is used. Instead, this PR uses the exported `transformWithOxc` function if available.
---

feat(plugin-vue): use `transformWithOxc` if `rolldown-vite` is detected

---

playground/ssr-vue/__tests__/ssr-vue.spec.ts
playground/tailwind-v3/__tests__/tailwind.spec.ts
playground/tailwind/__tests__/tailwind.spec.ts
playground/test-utils.ts
playground/vue-jsx/__tests__/vue-jsx.spec.ts
playground/vue-legacy/__tests__/vue-legacy.spec.ts
playground/vue/__tests__/vue.spec.ts
vitest.config.e2e.ts

Applied similar changes to https://github.com/vitejs/vite/pull/18699 and https://github.com/vitejs/vite/pull/20206
---

test: use `expect.poll` instead of `untilUpdated`

---

packages/plugin-vue/src/handleHotUpdate.ts

This plugin only handles js module nodes so this plugin should not filter out non-js modules nodes.
---

fix(hmr): ignore non-js modules

---

playground/vue-jsx-ts-built-in/vite.config.js
playground/vue-jsx/vite.config.js

```
(!) Experimental optimizeDeps.disabled and deps pre-bundling during build were removed in Vite 5.1.
To disable the deps optimizer, set optimizeDeps.noDiscovery to true and optimizeDeps.include as undefined or empty.
Please remove optimizeDeps.disabled from your config.
```

test: remove deprecated `optimizeDeps.disabled: true`

---

playground/vue-jsx-ts-built-in/package.json
playground/vue-jsx-ts-built-in/vite.config.js
pnpm-lock.yaml

Use `@rollup/plugin-swc` with rolldown-vite for ecma decorators as Oxc / rolldown-vite does not support lowering ecma decorators yet (https://github.com/oxc-project/oxc/issues/9170).
---

test: use `@rollup/plugin-swc` with rolldown-vite for ecma decorators
